import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8')),w=Array.isArray(raw)?raw[0]:raw;
const code=w.nodes.find(n=>n.name==='Prepare Inventory Review Batches').parameters.jsCode;
const mk=(claim,rank)=>({claim_number:claim,claim_id:`C${claim}`,claim:`fact ${claim}`,evidence_ids:['S1'],visual_target:`target ${claim}`,search_query_en:`subject detail ${claim}`,research_rows:[{id:'S1',snippet:'evidence'},{id:'S2',snippet:'evidence2'}],fingerprinted_candidates:[...Array(6)].map((_,i)=>({provider:'test',provider_asset_id:`${claim}-${i}`,candidate_id:`test:${claim}-${i}`,asset_identity:`test:${claim}-${i}`,target_anchor_pass:true,visual_hash:crypto.createHash('sha256').update(`${claim}-${i}`).digest('hex'),preview_urls:[`https://example.invalid/${claim}-${i}.jpg`]}))});
const rows=[1,2,3,4].map(c=>({json:mk(c)}));
const base={target_duration_seconds:15,canonical_subject:'subject',user_intent:'explain',research_rows:[{id:'S1',snippet:'evidence'},{id:'S2',snippet:'evidence2'}],candidate_claims:[1,2,3,4].map(c=>({claim_id:`C${c}`,claim:`fact ${c}`,evidence_ids:['S1'],visual_target:`target ${c}`}))};
const out=new Function('$input','$',code)({all:()=>rows},()=>({first:()=>({json:base})}));
const exposed=out.reduce((n,b)=>n+b.json.review_inventory_stats.unique_exposed,0);
assert.equal(exposed,24,'15s four-claim inventory must expose the full 24-image reviewer batch budget when unique assets exist');
console.log('INVENTORY_REVIEW_BUDGET_REGRESSION_PASS');
