import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));
const w=Array.isArray(raw)?raw[0]:raw;
const node=new Map(w.nodes.map(n=>[n.name,n])).get('Prepare Inventory Review Batches');
assert(node,'Prepare Inventory Review Batches missing');
const code=node.parameters.jsCode;
const run=new Function('$input','$',code);
const mk=(claim_number,h1,h2)=>({json:{claim_number,claim_id:`C${claim_number}`,claim:`grounded fact ${claim_number} includes a non-visible purpose`,evidence_ids:[claim_number%2?'S1':'S2'],visual_target:`visible target ${claim_number}`,search_query_en:`subject detail ${claim_number}`,research_rows:[{id:'S1',snippet:'evidence one'},{id:'S2',snippet:'evidence two'}],fingerprinted_candidates:[1,2].map((rank)=>({provider:'pexels',provider_asset_id:`${claim_number}-${rank}`,candidate_id:`pexels:${claim_number}-${rank}`,asset_identity:`pexels:${claim_number}-${rank}`,target_anchor_pass:true,visual_hash:rank===1?h1:h2,preview_urls:[`https://example.invalid/${claim_number}-${rank}.jpg`],title:`visible target ${claim_number}`}))}});
const rows=[mk(1,'0'.repeat(64),'1'.repeat(64)),mk(2,'3'.repeat(64),'4'.repeat(64)),mk(3,'f'.repeat(64),'e'.repeat(64)),mk(4,'a'.repeat(64),'b'.repeat(64))];
const base={target_duration_seconds:15,canonical_subject:'Named subject',user_intent:'explain',research_rows:[{id:'S1',snippet:'evidence one'},{id:'S2',snippet:'evidence two'}],candidate_claims:rows.slice(0,4).map((r,i)=>({claim_number:i+1,claim_id:`C${i+1}`,claim:`grounded fact ${i+1} includes a non-visible purpose`,evidence_ids:[i%2?'S2':'S1'],visual_target:`visible target ${i+1}`}))};
const out=run({all:()=>rows.slice(0,4)},name=>{assert.equal(name,'Validate Candidate Claims');return {first:()=>({json:base})}});
assert.equal(out.length,1);
const prompt=out[0].json.visual_review_request.input[0].text;
assert.match(prompt,/FACT text is independently grounded by the cited research evidence/);
assert.match(prompt,/pixels directly and truthfully match that claim's TARGET/);
assert.match(prompt,/TARGET is the full visual acceptance criterion and must not be relaxed/);
assert.match(prompt,/may illustrate a grounded FACT without independently proving factual details/);
assert.match(prompt,/Do not infer an unshown mechanism, numerical measurement, purpose, causality or hidden internal/);
assert.doesNotMatch(prompt,/pixels directly and truthfully illustrate ONE factual claim/);
const selector=new Map(w.nodes.map(n=>[n.name,n])).get('Select Verified Claim Inventory').parameters.jsCode;
assert.match(selector,/v\?\.relevant!==true/);
assert.match(selector,/supported_claim_id/);
assert.match(selector,/metadata_consistency_hits/);
assert.match(selector,/verified_visual_assets/);
assert.match(selector,/global-reviewed-context-v1/);
assert.doesNotMatch(selector,/claimAssets\.length<2/);
console.log('INVENTORY_VISUAL_TARGET_REVIEW_CONTRACT_REGRESSION_PASS');
