import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));
const w=Array.isArray(raw)?raw[0]:raw;
const node=w.nodes.find(n=>n.name==='Prepare Inventory Review Batches');
assert(node,'Prepare Inventory Review Batches missing');
const code=node.parameters.jsCode;
const hashes=['0','1','3','4','f','e'].map(x=>x.repeat(64));
const rows=[1,2,3].map((claim_number,i)=>({json:{claim_number,claim_id:`C${claim_number}`,claim:`Grounded fact ${claim_number} includes a non-visible function.`,evidence_ids:[claim_number%2?'S1':'S2'],editorial_role:claim_number===1?'hook':claim_number===2?'mechanism':'context',visual_form:claim_number===3?'map':'photo',visual_target:claim_number===3?'named reservoir map':`named physical component ${claim_number}`,search_query_en:`named subject component ${claim_number}`,fingerprinted_candidates:[0,1].map(rank=>({provider:'wikimedia',provider_asset_id:`${claim_number}-${rank}`,candidate_id:`wikimedia:${claim_number}-${rank}`,asset_identity:`wikimedia:${claim_number}-${rank}`,target_anchor_pass:true,visual_hash:hashes[i*2+rank],preview_urls:[`https://example.invalid/${claim_number}-${rank}.jpg`],title:`named target ${claim_number}`}))}}));
const base={target_duration_seconds:15,canonical_subject:'Named subject',user_intent:'Explain how it works',research_rows:[{id:'S1',snippet:'evidence one'},{id:'S2',snippet:'evidence two'}],candidate_claims:rows.map(x=>x.json)};
const out=new Function('$input','$',code)({all:()=>rows},name=>{assert.equal(name,'Validate Candidate Claims');return {first:()=>({json:base})}});
const prompt=out[0].json.visual_review_request.input[0].text;
assert.match(prompt,/supported_claim_id is a TARGET\/FORM binding, not a second factual-proof verdict/);
assert.match(prompt,/Do NOT reject a target-matching image merely because a still image cannot prove the FACT's function, purpose, causality, result, quantity, or operation/);
assert.match(prompt,/For a map or diagram target, visible labels and depicted geometry may establish subject identity/);
assert.match(prompt,/For a physical-component target, the component itself in authentic subject context is sufficient/);
assert.match(prompt,/Continue to reject wrong subjects, wrong forms, generic lookalikes without visible subject identity/);
assert.match(prompt,/TARGET is the full visual acceptance criterion and must not be relaxed/);
assert.doesNotMatch(prompt,/Panama|Gatun|Miraflores|canal lock/i,'binding clarification must remain topic-generic');
console.log('INVENTORY_VISUAL_BINDING_PRIORITY_REGRESSION_PASS');
