import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));const w=Array.isArray(raw)?raw[0]:raw;const nodes=new Map(w.nodes.map(n=>[n.name,n]));
const prep=nodes.get('Prepare Candidate Claims').parameters.jsCode;
const base={topic:'topic',resolved_subject:'Named subject mechanism',canonical_subject:'Named subject',user_intent:'explain operation',target_duration_seconds:15,language_code:'en',research_rows:[{id:'S1',title:'one',snippet:'fact one',url:'https://example.invalid/1'},{id:'S2',title:'two',snippet:'fact two',url:'https://example.invalid/2'}],candidate_claim_range:[6,6],exploration_queries:[{query_id:'Q1'}]};
const available_visual_assets=Array.from({length:6},(_,i)=>({inventory_id:`V${i+1}`,provider:'fixture',provider_asset_id:`P${i+1}`,candidate_id:`fixture:${i+1}`,preclaim_visual_form:i===1?'diagram':'photo',preclaim_visible_description:i===0?'Named subject steel miter lock gates':`Named subject component ${i+1}${i===1?' diagram':''}`,title:i===0?'Named subject steel miter lock gates':`Named subject component ${i+1}`,description:'Named subject physical component',categories:'Named subject'}));
const inventory={preclaim_review_version:'pre-claim-vision-reviewed-inventory-v1',available_visual_assets};
const out=new Function('$input','$',prep)({first:()=>({json:inventory})},name=>{assert.equal(name,'Validate Visual Exploration');return {first:()=>({json:base})}})[0].json;
assert.equal(out.available_visual_assets.length,6);
assert.match(out.claim_prompt,/Real licensed provider images have already been visually reviewed/);
assert.match(out.claim_prompt,/AVAILABILITY IS BINDING/);
assert.match(out.claim_prompt,/inventory_asset_ids/);
assert.match(out.claim_prompt,/do not invent a target and hope search finds it later/i);
assert.deepEqual(out.candidate_claim_range,[6,6]);
const validate=nodes.get('Validate Candidate Claims').parameters.jsCode;
const roles=['hook','mechanism','detail','result','context','establish'];
const mk=(badTarget=null)=>Array.from({length:6},(_,i)=>({claim_id:`C${i+1}`,claim:`Grounded fact ${i+1}.`,evidence_ids:[i%2?'S2':'S1'],editorial_role:roles[i],visual_form:i===1?'diagram':'photo',visual_target:i===0?(badTarget??'steel miter lock gates'):`Named subject component ${i+1}`,search_query_en:`Named subject component ${i+1}`,inventory_asset_ids:[`V${i+1}`]}));
const run=(claims)=>new Function('$input','$',validate)({first:()=>({json:{text:JSON.stringify({claims})}})},name=>{assert.equal(name,'Prepare Candidate Claims');return {first:()=>({json:out})}});
const valid=run(mk())[0].json.candidate_claims;assert.equal(valid.length,6);assert.equal(valid[0].inventory_asset_ids[0],'V1');
assert.throws(()=>run(mk('close-up showing steel miter lock gates during operation')),/compact observable visual_target/);
const invented=mk();invented[0].visual_target='unrepresented quantum widget';assert.throws(()=>run(invented),/not represented in cited real inventory/);
const badId=mk();badId[0].inventory_asset_ids=['V999'];assert.throws(()=>run(badId),/invalid availability asset IDs/);
console.log('INVENTORY_CLAIM_VISUALIZABILITY_CONTRACT_REGRESSION_PASS');
