import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateDiagramSpec,compileDiagramSpec} from '../services/media-worker/src/diagram-compiler.mjs';
const split={shot_id:'S2A',grounded_fact_ids:['S8'],archetype:'split',entities:[{id:'sun',label:'Sun',role:'input',shape:'circle',lane:'left'},{id:'white',label:'White light',role:'flow',shape:'box',lane:'center'},{id:'blue',label:'Blue',role:'output',shape:'box',lane:'right'},{id:'red',label:'Red',role:'output',shape:'box',lane:'right'}],relations:[{from:'sun',to:'white',kind:'emits',phase:1},{from:'white',to:'blue',kind:'splits',phase:2},{from:'white',to:'red',kind:'splits',phase:2}]};
const v1=validateDiagramSpec(split,{expectedShotId:'S2A',allowedFactIds:['S8']});
assert.equal(v1.entities.find(e=>e.id==='white').role,'process');
assert.equal(compileDiagramSpec(split,4,{expectedShotId:'S2A',allowedFactIds:['S8']}).source.compiler,'diagram-compiler-v1');
const flow={shot_id:'S3A',grounded_fact_ids:['S1'],archetype:'flow',short_title:'Light path',entities:[{id:'sun',label:'Sun',role:'source',shape:'circle'},{id:'air',label:'Air',role:'process',shape:'box'},{id:'blue',label:'Blue',role:'output',shape:'arrow'}],relations:[{from:'sun',to:'air',kind:'enters',phase:1},{from:'air',to:'blue',kind:'scatters',phase:2},{from:'blue',to:'viewer',kind:'reaches',phase:3}]};
const v2=validateDiagramSpec(flow,{expectedShotId:'S3A',allowedFactIds:['S1']});
assert.equal(v2.entities.find(e=>e.id==='sun').role,'input');
assert.equal(v2.title,'Light path');
assert.equal(v2.entities.find(e=>e.id==='blue').shape,'pill');
assert.equal(v2.relations[0].kind,'flow');
assert.equal(v2.relations[1].kind,'emits');
assert.equal(v2.relations.length,2);
const comparison={shot_id:'S4A',grounded_fact_ids:['S2'],archetype:'comparison',entities:[{id:'metric',label:'Scattering',role:'input'},{id:'result',label:'Intensity',role:'output'},{id:'blue',label:'Blue',role:'subject',shape:'bar'},{id:'red',label:'Red',role:'subject',shape:'bar'}],relations:[{from:'blue',to:'result',kind:'joins',phase:1},{from:'red',to:'result',kind:'joins',phase:1}]};
const v3=validateDiagramSpec(comparison,{expectedShotId:'S4A',allowedFactIds:['S2']});
assert.equal(v3.entities.find(e=>e.id==='blue').lane,'left');
assert.equal(v3.entities.find(e=>e.id==='red').lane,'right');
assert.equal(v3.entities.find(e=>e.id==='metric').lane,'center');
assert.equal(v3.entities.find(e=>e.id==='blue').shape,'box');
assert.doesNotThrow(()=>compileDiagramSpec(comparison,4,{expectedShotId:'S4A',allowedFactIds:['S2']}));
const wfRaw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));const wf=Array.isArray(wfRaw)?wfRaw[0]:wfRaw;const code=wf.nodes.find(n=>n.name==='Validate Storyboard').parameters.jsCode;
assert.match(code,/rawRole==='flow'\?'process':rawRole==='source'\?'input':rawRole/);
assert.match(code,/comparison lanes are invalid/);
assert.match(code,/d\.short_title/);
assert.match(code,/rawShape==='arrow'\?'pill':rawShape==='bar'\?'box':rawShape/);
assert.match(code,/rawKind==='enters'\?'flow':rawKind==='scatters'\?'emits':rawKind==='reaches'\?'flow':rawKind/);
console.log('V6_DIAGRAM_ROLE_ALIAS_REGRESSION_PASS');
