import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/V6-model-gateway.json','utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const by=new Map(wf.nodes.map((node)=>[node.name,node]));
const names=wf.nodes.map((node)=>node.name), ids=wf.nodes.map((node)=>node.id);
assert.equal(new Set(names).size,names.length,'V6 gateway node names must be unique');
assert.equal(new Set(ids).size,ids.length,'V6 gateway node IDs must be unique');
assert.equal(wf.name,'V6 — Free-Only Text Model Gateway');
assert.equal(by.get('Webhook')?.parameters?.path,'v6-model-gateway');
assert.ok(Array.isArray(wf.shared)&&wf.shared.some((s)=>s.role==='workflow:owner'),'V6 gateway must preserve owner ACL');
const serialized=JSON.stringify(wf).toLowerCase();
for(const forbidden of ['gemini','generativelanguage.googleapis.com','google_gemini','openai/','anthropic/','stepfun/step-3.7-flash','nex-agi/']) assert.equal(serialized.includes(forbidden),false,`V6 gateway contains forbidden/unproven provider marker: ${forbidden}`);
const build=by.get('Build Request')?.parameters?.jsCode??'';
assert.match(build,/nvidia\/nemotron-3-super-120b-a12b:free/);
assert.match(build,/inclusionai\/ling-3\.0-flash-sante:free/);
assert.match(build,/route==='storyboard'/);
assert.match(build,/text-only/);
const model=by.get('Kilo Free Model');
assert.equal(model?.parameters?.url,'https://api.kilo.ai/api/gateway/chat/completions');
assert.equal(model?.parameters?.options?.timeout,"={{ $json.route === 'storyboard' ? 65000 : 50000 }}",'V6 storyboard route uses measured 65s bound; other routes remain 50s');
assert.equal(wf.connections?.['Build Request']?.main?.[0]?.[0]?.node,'Kilo Free Model');
assert.equal(wf.connections?.['Normalize Free Model Response']?.main?.[0]?.[0]?.node,'Use Semantic Fallback?');
assert.equal(wf.connections?.['Use Semantic Fallback?']?.main?.[1]?.[0]?.node,'Respond');
const normalize=by.get('Normalize Free Model Response')?.parameters?.jsCode??'';
assert.match(normalize,/provider_exhausted:!success/);
assert.match(normalize,/kilo-\$\{ctx\.route\}/);
console.log('V6_FREE_ONLY_MODEL_GATEWAY_REGRESSION_PASS');
