import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/V6-model-gateway.json','utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const by=new Map(wf.nodes.map((node)=>[node.name,node]));
assert.equal(wf.name,'V6 — Free-Only Text Model Gateway');
assert.equal(by.get('Webhook')?.parameters?.path,'v6-model-gateway');
const serialized=JSON.stringify(wf).toLowerCase();
for(const forbidden of ['gemini','generativelanguage.googleapis.com','google_gemini','openai','anthropic']) assert.equal(serialized.includes(forbidden),false,`V6 gateway contains forbidden provider marker: ${forbidden}`);
const build=by.get('Build Request')?.parameters?.jsCode??'';
assert.match(build,/stepfun\/step-3\.7-flash:free/);
assert.match(build,/text-only/);
assert.equal(by.get('Kilo Free Model')?.parameters?.url,'https://api.kilo.ai/api/gateway/chat/completions');
assert.ok(Number(by.get('Kilo Free Model')?.parameters?.options?.timeout)<=90000,'Kilo timeout must stay bounded');
const branches=wf.connections?.['Kilo Succeeded?']?.main??[];
assert.equal(branches?.[0]?.[0]?.node,'Normalize Kilo Success');
assert.equal(branches?.[1]?.[0]?.node,'Normalize Kilo Failure');
assert.equal(wf.connections?.['Normalize Kilo Failure']?.main?.[0]?.[0]?.node,'Respond');
const failureCode=by.get('Normalize Kilo Failure')?.parameters?.jsCode??'';
const failed=new Function('$json',failureCode)({provider_attempts:[{provider:'kilo',success:false}]})[0].json;
assert.equal(failed.provider_exhausted,true);
assert.equal(failed.provider,'none');
assert.equal(failed.text,'');
assert.equal(failed.provider_attempts.length,1);
console.log('V6_FREE_ONLY_MODEL_GATEWAY_REGRESSION_PASS');
