import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/V6-model-gateway.json','utf8'));const wf=Array.isArray(raw)?raw[0]:raw;const by=new Map(wf.nodes.map(n=>[n.name,n]));
const build=by.get('Build Request').parameters.jsCode;
assert.match(build,/route==='resolution'/);
assert.match(build,/\(route==='semantic'\|\|route==='resolution'\|\|route==='final_story'\)\?'liquid\/lfm-2\.5-2\.6b:free'/);
assert.match(build,/route==='semantic'\|\|route==='resolution'\|\|route==='final_story'\)model_request_body\.include_reasoning=false/);
const gate=JSON.stringify(by.get('Use Semantic Fallback?').parameters);
assert.match(gate,/route === 'resolution'/);
console.log('V6_RESOLUTION_LIQUID_ROUTE_PASS');
