import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const by=new Map(wf.nodes.map((n)=>[n.name,n]));
for(const name of ['Prepare Storyboard Director','Build Storyboard Director Request','Direct Storyboard','Validate Storyboard','Build Storyboard Discovery Request','Discover Storyboard Media','Freeze Storyboard Feasibility','Prepare Final Story Request','Write Final Story','Build Final Storyboard Story','Persist Storyboard First Story','Require Persisted Storyboard Story']) assert.ok(by.has(name),`missing ${name}`);
for(const retired of ['Prepare Visual Exploration','Draft Visual Exploration','Prepare Pre-Claim Review Batches','Inline Pre-Claim Candidate Images','Review Pre-Claim Visual Inventory','Select Pre-Claim Visual Inventory','Prepare Candidate Claims','Draft Candidate Claims','Prepare Inventory Grounded Story','Write Inventory Grounded Story','Build Final Inventory Story']) assert.equal(by.has(retired),false,`retired mandatory visual-review node still present: ${retired}`);
const serialized=JSON.stringify(wf).toLowerCase();
assert.equal(serialized.includes('/webhook/v4-model-gateway'),false,'WF02 must not call legacy V4 model gateway');
assert.equal(serialized.includes('gemini'),false,'WF02 must not contain Gemini in V6 active path');
assert.equal(serialized.includes('inline-review-images'),false,'WF02 must not inline image batches for mandatory visual review');
assert.equal(by.get('Direct Storyboard').parameters.url,'http://127.0.0.1:5678/webhook/v6-model-gateway');
assert.equal(by.get('Write Final Story').parameters.url,'http://127.0.0.1:5678/webhook/v6-model-gateway');
const validate=by.get('Validate Storyboard').parameters.jsCode;
assert.match(validate,/representation==='diagram'/);
assert.match(validate,/raw geometry is forbidden/);
assert.match(validate,/external-media establishing shot/);
const freeze=by.get('Freeze Storyboard Feasibility').parameters.jsCode;
assert.match(freeze,/deterministic-metadata-geometry-v1/);
assert.match(freeze,/constructed-grounded-diagram-v1/);
assert.match(freeze,/no deterministic executable media/);
const final=by.get('Build Final Storyboard Story').parameters.jsCode;
assert.match(final,/version:'storyboard-first-v1'/);
assert.match(final,/representation-first-v1/);
const persist=by.get('Persist Storyboard First Story').parameters.query;
assert.match(persist,/story_package->>'version'='storyboard-first-v1'/);
const route=(from,to)=>assert.equal(wf.connections?.[from]?.main?.[0]?.[0]?.node,to,`${from} must route to ${to}`);
route('Research Resolved Subject','Prepare Storyboard Director');
route('Validate Storyboard','Build Storyboard Discovery Request');
route('Discover Storyboard Media','Freeze Storyboard Feasibility');
route('Freeze Storyboard Feasibility','Prepare Final Story Request');
route('Write Final Story','Build Final Storyboard Story');
route('Require Persisted Storyboard Story','Start Voiceover Generation');
for(const node of wf.nodes.filter((n)=>n.type==='n8n-nodes-base.code')) new Function('$','$input',node.parameters.jsCode);
console.log('V6_STORYBOARD_FIRST_PLANNING_REGRESSION_PASS');
