import assert from 'node:assert/strict';
import fs from 'node:fs';
const gwRaw=JSON.parse(fs.readFileSync('n8n/workflows/V6-model-gateway.json','utf8'));const gw=Array.isArray(gwRaw)?gwRaw[0]:gwRaw;const by=new Map(gw.nodes.map(n=>[n.name,n]));
const build=by.get('Build Request').parameters.jsCode;
assert.match(build,/route==='final_story'/);
assert.match(build,/route==='semantic'\|\|route==='resolution'\|\|route==='final_story'/);
assert.match(build,/liquid\/lfm-2\.5-2\.6b:free/);
assert.match(build,/structured_transport='response_format'/);
assert.match(build,/response_format=\{type:'json_object'\}/);
assert.doesNotMatch(build,/final_story structured route requires response_schema/);
const norm=by.get('Normalize Free Model Response').parameters.jsCode;
assert.match(norm,/validateSchema/);
assert.match(norm,/schemaValid/);
assert.match(norm,/deferSchemaValidation=ctx.route==='storyboard'/);
const wfRaw=JSON.parse(fs.readFileSync('n8n/workflows/WF02-plan-script-and-scenes.json','utf8'));const wf=Array.isArray(wfRaw)?wfRaw[0]:wfRaw;
const finalReq=wf.nodes.find(n=>n.name==='Prepare Final Story Request').parameters.jsCode;
assert.match(finalReq,/response_schema:schema,route:'final_story'/);
console.log('V6_FINAL_STORY_STRUCTURED_JSON_PASS');
