import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync(new URL('../n8n/workflows/WF02-plan-script-and-scenes.json',import.meta.url),'utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const nodes=new Map(wf.nodes.map(n=>[n.name,n]));
const chain=['Research Resolved Subject','Prepare Candidate Claims','Build Draft Candidate Claims Request','Draft Candidate Claims','Validate Candidate Claims','Discover Pre-Script Visual Inventory','Expand Inventory Fingerprint Items','Fingerprint Inventory Candidates','Attach Inventory Fingerprints','Prepare Inventory Review Batches','Inline Inventory Candidate Images','Build Review Inventory Candidate Images Request','Review Inventory Candidate Images','Select Verified Claim Inventory','Prepare Inventory Grounded Story','Build Write Inventory Grounded Story Request','Write Inventory Grounded Story','Build Final Inventory Story','Persist Inventory First Story','Require Persisted Inventory Story','Start Voiceover Generation'];
for(const name of chain)assert(nodes.has(name),`missing ${name}`);
const edge=(a,b)=>wf.connections[a]?.main?.[0]?.some(x=>x.node===b);
for(let i=0;i<chain.length-1;i++)assert(edge(chain[i],chain[i+1]),`missing causal edge ${chain[i]} -> ${chain[i+1]}`);
const source=fs.readFileSync(new URL('../n8n/workflows/WF02-plan-script-and-scenes.json',import.meta.url),'utf8');
assert(!/Prepare Grounded Script Prompt|Write Grounded Natural Script|Build Final Grounded Script/u.test(source));
assert.match(nodes.get('Prepare Candidate Claims').parameters.jsCode,/Do NOT write the final narration yet/);
assert.match(nodes.get('Discover Pre-Script Visual Inventory').parameters.jsonBody,/inventory_request/);
assert.match(nodes.get('Prepare Inventory Review Batches').parameters.jsCode,/BEFORE a short-video script is written/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/target_anchor_pass.*true/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/hamming\(hash,h\)<=18/);
assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/verified real image reserved before narration/);
const final=nodes.get('Build Final Inventory Story').parameters.jsCode;
assert.match(final,/inventory-first-story-v1/);
assert.match(final,/evidence_ids:u\.evidence_ids/);
assert(!/index%selected_evidence|index%.*evidence|visual_search_queries_en/u.test(final),'final story must not use modulo provenance or late visual queries');
const persist=nodes.get('Persist Inventory First Story').parameters.query;
assert.match(persist,/story_package/);
assert.match(persist,/visual_search_queries_en=NULL/);
assert.match(persist,/jsonb_array_length\(i\.story_package->'assets'\)=jsonb_array_length\(i\.story_package->'units'\)/);
for(const node of wf.nodes.filter(n=>n.type==='n8n-nodes-base.code')) new Function('$input','$',node.parameters.jsCode);
console.log('WF02_INVENTORY_FIRST_STORY_REGRESSION_PASS');
