import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync(new URL('../n8n/workflows/WF02-plan-script-and-scenes.json',import.meta.url),'utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const nodes=new Map(wf.nodes.map(n=>[n.name,n]));
const chain=['Research Resolved Subject','Prepare Visual Exploration','Build Draft Visual Exploration Request','Draft Visual Exploration','Validate Visual Exploration','Discover Pre-Claim Visual Inventory','Prepare Pre-Claim Review Batches','Inline Pre-Claim Candidate Images','Build Review Pre-Claim Visual Inventory Request','Review Pre-Claim Visual Inventory','Select Pre-Claim Visual Inventory','Prepare Candidate Claims','Build Draft Candidate Claims Request','Draft Candidate Claims','Validate Candidate Claims','Discover Pre-Script Visual Inventory','Expand Inventory Fingerprint Items','Fingerprint Inventory Candidates','Attach Inventory Fingerprints','Prepare Inventory Review Batches','Inline Inventory Candidate Images','Build Review Inventory Candidate Images Request','Review Inventory Candidate Images','Select Verified Claim Inventory','Prepare Inventory Grounded Story','Build Write Inventory Grounded Story Request','Write Inventory Grounded Story','Build Final Inventory Story','Persist Inventory First Story','Require Persisted Inventory Story','Start Voiceover Generation'];
for(const name of chain)assert(nodes.has(name),`missing ${name}`);
const edge=(a,b)=>wf.connections[a]?.main?.[0]?.some(x=>x.node===b);
for(let i=0;i<chain.length-1;i++)assert(edge(chain[i],chain[i+1]),`missing causal edge ${chain[i]} -> ${chain[i+1]}`);
const source=fs.readFileSync(new URL('../n8n/workflows/WF02-plan-script-and-scenes.json',import.meta.url),'utf8');
assert(!/Prepare Grounded Script Prompt|Write Grounded Natural Script|Build Final Grounded Script/u.test(source));
assert.match(nodes.get('Prepare Visual Exploration').parameters.jsCode,/discover what real images actually exist before story planning/);assert.match(nodes.get('Discover Pre-Claim Visual Inventory').parameters.jsonBody,/exploration_request/);assert.match(nodes.get('Prepare Candidate Claims').parameters.jsCode,/Real licensed provider images have already been visually reviewed/);assert.match(nodes.get('Prepare Candidate Claims').parameters.jsCode,/AVAILABILITY IS BINDING/);assert.match(nodes.get('Prepare Candidate Claims').parameters.jsCode,/inventory_asset_ids/);
assert.match(nodes.get('Discover Pre-Script Visual Inventory').parameters.jsonBody,/inventory_request/);
assert.match(nodes.get('Prepare Inventory Review Batches').parameters.jsCode,/BEFORE a short-video script is written/);
assert.match(nodes.get('Prepare Inventory Review Batches').parameters.jsCode,/retrieval hypothesis.*must not force acceptance/);
assert.match(nodes.get('Prepare Inventory Review Batches').parameters.jsCode,/FULL RESEARCH CORPUS/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/target_anchor_pass.*true/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/hamming\(hash,h\)<=18/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/supported_claim_id/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/verified_visual_assets/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/global-reviewed-context-v1/);
assert.match(nodes.get('Select Verified Claim Inventory').parameters.jsCode,/origin_claim_id/);
assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/Factual grounding and visual grounding are separate/);assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/GLOBAL REVIEWER-APPROVED VISUAL POOL/);assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/REQUIRED GROUNDED CLAIM IDS/);assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/required_claim_ids:requiredClaimIds/);assert.match(nodes.get('Prepare Inventory Grounded Story').parameters.jsCode,/shot_plan/);
const final=nodes.get('Build Final Inventory Story').parameters.jsCode;
assert.match(final,/inventory-first-story-v1/);
assert.match(final,/evidence_ids:u\.evidence_ids/);
assert.match(final,/shot_assets:nested/);
assert.match(final,/asset_ids:assetIds/);assert.match(final,/grounded_claim=clean\(c\.claim\)/);assert.match(final,/editorial_contract_version:'shot-intent-v1'/);assert.match(final,/shot_plan:plan/);assert.match(final,/editorial_role:c\.editorial_role/);assert.match(final,/visual_form:c\.visual_form/);assert.match(final,/visual_binding_mode:'global-reviewed-context-v1'/);assert.match(final,/omitted required explanatory claim/);
assert(!/index%selected_evidence|index%.*evidence|visual_search_queries_en/u.test(final),'final story must not use modulo provenance or late visual queries');
const storyReq=nodes.get('Build Write Inventory Grounded Story Request').parameters.jsCode;assert.match(storyReq,/\"minItems\":minUnits/);assert.match(storyReq,/\"maxItems\":maxUnits/);
const persist=nodes.get('Persist Inventory First Story').parameters.query;
assert.match(persist,/story_package/);
assert.match(persist,/visual_search_queries_en=NULL/);
assert.match(persist,/jsonb_array_length\(i\.story_package->'assets'\)=jsonb_array_length\(i\.story_package->'units'\)/);
assert.match(persist,/RETURNING j\.id,jsonb_array_length\(j\.story_package->'units'\)::int AS story_unit_count/);
assert.match(persist,/\(SELECT story_unit_count FROM upd\) story_unit_count/);
assert.doesNotMatch(persist,/SELECT jsonb_array_length\(story_package->'units'\) FROM public\.jobs/,'data-modifying CTE must verify persisted story through UPDATE RETURNING, not same-snapshot table reread');
for(const node of wf.nodes.filter(n=>n.type==='n8n-nodes-base.code')) new Function('$input','$',node.parameters.jsCode);
console.log('WF02_INVENTORY_FIRST_STORY_REGRESSION_PASS');
