import assert from 'node:assert/strict';import fs from 'node:fs';
const r=JSON.parse(fs.readFileSync('n8n/workflows/WF03-natural-edge-voice.json','utf8')),w=Array.isArray(r)?r[0]:r,by=new Map(w.nodes.map(n=>[n.name,n]));
const prepare=by.get('Prepare Duration Rewrite').parameters.jsCode,build=by.get('Build Rewrite Narration For Exact Duration Request').parameters.jsCode,apply=by.get('Apply Duration Rewrite').parameters.jsCode;
const units=[
{unit_id:'U1',claim_id:'C1',grounded_claim:'The Panama Canal uses a series of massive lock chambers to lift vessels 26 meters above sea level to cross the continental divide.',narration:'Панамский канал использует гигантские шлюзовые камеры, чтобы поднимать суда на 26 метров над уровнем моря для преодоления континентального водораздела.',evidence_ids:['S2','S8','S10'],asset_id:'A3',editorial_role:'hook'},
{unit_id:'U2',claim_id:'C3',grounded_claim:'Internal lock culverts act as large tunnels that allow water to flow into and out of the chambers to control water levels.',narration:'Внутренние бетонные водопропускные туннели позволяют воде наполнять или опорожнять камеры, управляя уровнем воды для плавного перемещения кораблей.',evidence_ids:['S3'],asset_id:'A2',editorial_role:'mechanism'},
{unit_id:'U3',claim_id:'C6',grounded_claim:'Ships are successfully lowered on the opposite side of the continental divide, returning them to sea level to continue their journey.',narration:'После прохода через систему шлюзов суда плавно опускаются на противоположной стороне, возвращаясь к уровню моря для продолжения своего пути.',evidence_ids:['S4','S8'],asset_id:'A5',editorial_role:'result'}];
const story={version:'inventory-first-story-v1',units,assets:[{asset_id:'A3'},{asset_id:'A2'},{asset_id:'A5'}]},script_text=units.map(u=>u.narration).join(' '),input={fit_pass:0,max_fit_passes:1,story_package:story,script_text,language_code:'ru',target_duration_seconds:15,duration_seconds:25.983,fit_history:[],job_id:'b494d95a-03a0-4503-805e-49076652dfc0',provider:'microsoft_edge_readaloud',model:'edge_neural',voice:'ru-RU-DmitryNeural',edge_fallback_voice:'ru-RU-DmitryNeural'};
assert.equal(script_text.match(/[\p{L}\p{N}]+(?:[’'\-][\p{L}\p{N}]+)*/gu).length,55);
const base=new Function('$input',prepare)({first:()=>({json:input})})[0].json;assert.equal(base.semantic_word_floor,36);assert.equal(base.desired_word_target,36);assert.match(base.duration_controller_mode,/semantic_floor$/);assert.deepEqual(base.unit_order,['U1','U2','U3']);assert.equal(base.max_fit_passes,1);
const schema=new Function('$json',build)(base).json.model_request.response_schema;assert.equal(schema.properties.tokens.minItems,36);assert.equal(schema.properties.tokens.maxItems,36);
const block=(unit_id,words)=>words.map(word=>({unit_id,word})),good={tokens:[...block('U1',['Панамский','канал','поднимает','суда','шлюзами','на','двадцать','шесть','метров','над','уровнем','моря.']),...block('U2',['Внутренние','водопропускные','туннели','направляют','потоки','воды','в','камеры','и','обратно','регулируя','уровень.']),...block('U3',['Суда','затем','плавно','опускаются','шлюзами','на','другой','стороне','водораздела','до','уровня','моря.'])]};
const $=name=>{assert.equal(name,'Prepare Duration Rewrite');return{first:()=>({json:base})}};const out=new Function('$input','$',apply)({first:()=>({json:{text:JSON.stringify(good)}})},$)[0].json;assert.equal(out.script_text.match(/[\p{L}\p{N}]+(?:[’'\-][\p{L}\p{N}]+)*/gu).length,36);assert.equal(out.story_package.units.length,3);for(const u of out.story_package.units)assert.match(u.narration,/\.$/);assert.match(out.story_package.units[0].narration,/двадцать шесть метров/);assert.match(out.story_package.units[1].narration,/в камеры и обратно/);assert.match(out.story_package.units[2].narration,/водораздела.*уровня моря/);
const oldLive32={tokens:good.tokens.slice(0,32)};assert.throws(()=>new Function('$input','$',apply)({first:()=>({json:{text:JSON.stringify(oldLive32)}})},$),/total token count 32\/36/);
console.log('WF03_LIVE_SENTENCE_COMPLETION_REGRESSION_PASS');
