import assert from 'node:assert/strict';
import fs from 'node:fs';

const workflow=JSON.parse(fs.readFileSync(new URL('../n8n/workflows/WF03-natural-edge-voice.json',import.meta.url),'utf8'))[0];
const node=name=>workflow.nodes.find(n=>n.name===name);
for(const name of ['Final Narration Needs Visual Rebind','Prepare Final Visual Rebind','Rebind Visual Queries To Final Beats','Apply Final Visual Rebind']) assert.ok(node(name),`${name} missing`);
const prep=node('Prepare Final Visual Rebind').parameters.jsCode;
assert.match(prep,/FINAL BEATS/);
assert.match(prep,/query N must literally depict/);
assert.match(prep,/technical diagrams\/schematics are allowed and required/);
assert.match(prep,/no text cards/i);
const apply=node('Apply Final Visual Rebind').parameters.jsCode;
const run=new Function('$input','$',apply);
const beatTimings=Array.from({length:6},(_,i)=>({scene_number:i+1,narration:`beat ${i+1}`,beat_start_seconds:i*2.5,beat_end_seconds:(i+1)*2.5}));
const base={job_id:'00000000-0000-4000-8000-000000000001',target_duration_seconds:15,beat_timings:beatTimings,expected_visual_queries:6};
const queries=Array.from({length:6},(_,i)=>`specific visual for beat ${i+1}`);
const result=run({first:()=>({json:{text:JSON.stringify({visual_search_queries_en:queries})}})},name=>{assert.equal(name,'Prepare Final Visual Rebind');return{first:()=>({json:base})};})[0].json;
assert.deepEqual(result.visual_search_queries_en,queries);
assert.equal(result.needs_visual_rebind,false);
const persist=node('Persist Voiceover Result');
assert.match(persist.parameters.query,/visual_search_queries_en=i\.final_visual_queries/);
assert.match(persist.parameters.options.queryReplacement,/JSON\.stringify\(\$json\.visual_search_queries_en\)/);
const load=node('Load Voiceover Context').parameters.query;
assert.match(load,/j\.visual_search_queries_en/);
const prepareBeat=node('Prepare Beat Timings').parameters.jsCode;
assert.match(prepareBeat,/needs_visual_rebind:fitPasses>0/);
const c=workflow.connections;
assert.equal(c['Prepare Beat Timings'].main[0][0].node,'Final Narration Needs Visual Rebind');
assert.equal(c['Apply Final Visual Rebind'].main[0][0].node,'Persist Voiceover Result');
console.log('WF03_FINAL_VISUAL_REBIND_REGRESSION_PASS');
