import assert from 'node:assert/strict';
import fs from 'node:fs';
const r=JSON.parse(fs.readFileSync('n8n/workflows/WF04-visual-sourcing.json','utf8')),w=Array.isArray(r)?r[0]:r,by=new Map(w.nodes.map(n=>[n.name,n]));
for(const n of w.nodes.filter(n=>n.type==='n8n-nodes-base.code'))new Function('$input','$',n.parameters.jsCode);
const a=(id,provider,hash)=>({asset_id:id,provider,provider_asset_id:id,download_url:`https://x/${id}.jpg`,visual_hash:hash,visual_cluster_key:`preview:${hash}`,visible_description:`Photo ${id}`});
const a1=a('A1','wikimedia','0'.repeat(64)),a2=a('A2','pexels','3'.repeat(64)),a3=a('A3','wikimedia','f'.repeat(64)),a4=a('A4','pexels','c'.repeat(64));
const story={version:'inventory-first-story-v1',editorial_contract_version:'shot-intent-v1',units:[{unit_id:'U1',claim_id:'C1',narration:'One.',evidence_ids:['S1'],editorial_role:'hook',visual_form:'photo',asset_id:'A1',asset_ids:['A1','A2'],shot_plan:[{asset_id:'A1',shot_intent:'Notice first subject'},{asset_id:'A2',shot_intent:'Notice second subject'}]},{unit_id:'U2',claim_id:'C2',narration:'Two.',evidence_ids:['S2'],editorial_role:'mechanism',visual_form:'diagram',asset_id:'A3',asset_ids:['A3','A4'],shot_plan:[{asset_id:'A3',shot_intent:'Notice mechanism overview'},{asset_id:'A4',shot_intent:'Notice mechanism detail'}]}],assets:[{...a1,shot_assets:[a1,a2]},{...a3,shot_assets:[a3,a4]}]};
const j={job_exists:true,job_id:'11111111-1111-4111-8111-111111111111',content_model_version:'staged_v1',status:'processing',current_stage:'voiceover',voiceover_path:'jobs/a.wav',voiceover_duration_seconds:4,story_package:story,scenes:[{scene_number:1,narration:'One.',beat_start_seconds:0,beat_end_seconds:2,duration_seconds:2},{scene_number:2,narration:'Two.',beat_start_seconds:2,beat_end_seconds:4,duration_seconds:2}],existing_visual_segment_count:0,existing_visual_shot_count:0};
const out=new Function('$input',by.get('Require Eligible Visual Job').parameters.jsCode)({first:()=>({json:j})})[0].json;
assert.equal(out.story_unit_count,2);assert.equal(out.reserved_photo_count,4);
console.log('WF04_CODE_NODE_RUNTIME_REGRESSION_PASS');
