import assert from 'node:assert/strict';
import fs from 'node:fs';
const r=JSON.parse(fs.readFileSync('n8n/workflows/WF04-visual-sourcing.json','utf8')),w=Array.isArray(r)?r[0]:r,by=new Map(w.nodes.map(n=>[n.name,n]));
const persist=by.get('Persist Reserved Visual').parameters.query,complete=by.get('Verify Reserved Visual Completion').parameters.query;
assert.match(persist,/WITH existing_segment AS \(/);
assert.match(persist,/FROM public\.visual_segments vs\s+WHERE vs\.job_id=\$1::uuid AND vs\.segment_number=\$2::int FOR UPDATE/);
assert.match(persist,/inserted_segment AS \(/);
assert.match(persist,/CASE WHEN \$10::smallint=1 THEN 'ready' ELSE 'planned' END/);
assert.match(persist,/ON CONFLICT\(job_id,segment_number\) DO NOTHING/,'existing segment must not be modified once before the completion UPDATE');
assert.doesNotMatch(persist,/ON CONFLICT\(job_id,segment_number\) DO UPDATE/,'same visual segment row must not be updated twice in one statement');
assert.match(persist,/segment_shot_number/);
assert.match(persist,/s\.status='planned' AND NOT EXISTS\(SELECT 1 FROM inserted_segment/);
assert.match(persist,/EXISTS\(SELECT 1 FROM inserted i WHERE i\.visual_segment_id=vs\.id\)/);
assert.match(persist,/count\(\*\) FROM public\.visual_shots sh WHERE sh\.visual_segment_id=vs\.id\).*count\(\*\) FROM inserted/s);
assert.match(persist,/ns\.planned_shot_count=1/,'new one-shot segments must become ready without a second update of the inserted row');
assert.match(complete,/segment_count=q\.expected_count/);
assert.match(complete,/planned_shot_count=q\.shot_count/);
assert.match(complete,/post_freeze_search_used',false/);
console.log('WF04_SEGMENT_MULTISHOT_COMPLETION_REGRESSION_PASS');
