import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync(new URL('../n8n/workflows/WF04-visual-sourcing.json',import.meta.url),'utf8'));
const wf=Array.isArray(raw)?raw[0]:raw;
const by=new Map(wf.nodes.map(n=>[n.name,n]));
const attach=new Function('$json','$',by.get('Attach Rank Results').parameters.jsCode);
const ctx={segment_number:1,expected_visual_segment_count:2,planned_shot_count:2,candidate_pool:[{candidate_id:'x',preview_urls:['https://images.pexels.com/x.jpg']}]};
const $attach=name=>{assert.equal(name,'Expand Rank Items');return{item:{json:ctx}}};
const failed=attach({error:{message:'timeout of 120000ms exceeded'}},$attach).json;
assert.equal(failed.segment_number,1);
assert.match(failed.fingerprint_error,/timeout/i);
const ok={segment_number:2,expected_visual_segment_count:2,planned_shot_count:1,ranked_candidates:[{candidate_id:'y',media_kind:'photo',preview_urls:['https://images.pexels.com/y.jpg'],visual_hash:'0'.repeat(64)}],fingerprint_error:null};
const prepCode=by.get('Prepare Multimodal Visual Review').parameters.jsCode;
const prep=new Function('$input','$',prepCode);
const $prep=()=>{throw new Error('unexpected workflow lookup')};
assert.throws(()=>prep({all:()=>[{json:failed},{json:ok}]},$prep),/segment 1: timeout/i);
const rankNode=by.get('Rank Eligible Visuals');
assert.equal(rankNode.retryOnFail,true);
assert.equal(rankNode.maxTries,2);
console.log('WF04_FINGERPRINT_FAILURE_CARDINALITY_REGRESSION_PASS');
