import assert from 'node:assert/strict';
import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('n8n/workflows/WF05-video-render.json','utf8'));
const w=Array.isArray(raw)?raw[0]:raw;
const by=new Map(w.nodes.map(n=>[n.name,n]));
for(const name of ['Load Render Context','Require Eligible Render Job','Prepare Render Manifest','Render Video','Validate Render Result','Persist Render Success','Require Render Completion']) assert(by.has(name),`missing ${name}`);
const load=by.get('Load Render Context').parameters.query;
assert.match(load,/story_package/);assert.match(load,/final_video_sha256/);assert.match(load,/visual_segments/);assert.match(load,/visual_shots/);assert.match(load,/media_library_assets/);
const requireCode=by.get('Require Eligible Render Job').parameters.jsCode;
assert.match(requireCode,/inventory-first-story-v1/);assert.match(requireCode,/story\.units\.length/);assert.match(requireCode,/planned_shot_count/);assert.match(requireCode,/count!==1/);assert.match(requireCode,/reserved_before_script/);assert.match(requireCode,/post_freeze_search_used/);assert.doesNotMatch(requireCode,/15:6|30:10|45:14|60:18/);
const manifest=by.get('Prepare Render Manifest').parameters.jsCode;
assert.match(manifest,/visual_contract/);assert.match(manifest,/reserved_before_script:true/);assert.match(manifest,/post_freeze_search_used:false/);assert.match(manifest,/beats:/);assert.match(manifest,/shots:/);
assert.equal(by.get('Render Video').parameters.url,'http://media-worker:3001/render-v3');
const validate=by.get('Validate Render Result').parameters.jsCode;
assert.match(validate,/inventory-first-render-v1/);assert.match(validate,/full-image-preserve-v1/);assert.match(validate,/destructive_still_crop_count/);assert.match(validate,/artifact_sha256/);assert.match(validate,/rendered_visual_state_count/);assert.match(validate,/story_unit_count/);
const persist=by.get('Persist Render Success').parameters.query;
assert.match(persist,/final_video_sha256=\$3::text/);assert.match(persist,/inventory-first-render-v1/);assert.match(persist,/post_freeze_search_used/);
assert.match(by.get('Require Render Completion').parameters.jsCode,/final_video_sha256/);
const schema=fs.readFileSync('db/init/001_init.sql','utf8');assert.match(schema,/final_video_sha256 text/);assert.match(schema,/jobs_final_video_sha256_check/);
console.log('WF05_INVENTORY_RENDER_REGRESSION_PASS');
